# -*- coding: utf-8 -*-
"""dNBR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/lvsantarosa/Analyzing-burn-severity/blob/main/dNBR.ipynb
"""

import geemap
import ee

# Authenticate to Earth Engine
ee.Authenticate()
ee.Initialize()

# Construct a point from coordinates.
geometry = ee.Geometry.Point([-47.7330, -3.8850])

# Define a buffer around the point
bufferDistance = 10000
pointBuffer = geometry.buffer(bufferDistance)

# Choose dates for the pre-fire and post-fire period
preFireStartDate = ee.Date.fromYMD(2019, 6, 1)
preFireEndDate = ee.Date.fromYMD(2019, 8, 31)

postFireStartDate = ee.Date.fromYMD(2020, 6, 1)
postFireEndDate = ee.Date.fromYMD(2020, 8, 31)

# Function to mask clouds in Sentinel-2 data
def mask_s2_clouds(image):
    qa60 = image.select(['QA60'])
    cloud_mask = qa60.bitwiseAnd(1 << 10).eq(0).And(qa60.bitwiseAnd(1 << 11).eq(0))
    return image.updateMask(cloud_mask)

# Filter Sentinel-2 data for pre- and post-fire periods
    pre_fire_s2 = (
        ee.ImageCollection('COPERNICUS/S2')
        .filterBounds(pointBuffer)
        .filterDate(preFireStartDate, preFireEndDate)
        .map(mask_s2_clouds)
    )

    post_fire_s2 = (
        ee.ImageCollection('COPERNICUS/S2')
        .filterBounds(pointBuffer)
        .filterDate(postFireStartDate, postFireEndDate)
        .map(mask_s2_clouds)
    )

# Create median images for pre- and post-fire periods
    pre_fire_s2_median = pre_fire_s2.median().clip(pointBuffer)
    post_fire_s2_median = post_fire_s2.median().clip(pointBuffer)

# Calculate NBR for pre- and post-fire
    pre_fire_nbr = pre_fire_s2_median.normalizedDifference(['B8', 'B4']).rename('NBR').toFloat()
    post_fire_nbr = post_fire_s2_median.normalizedDifference(['B8', 'B4']).rename('NBR').toFloat()

    # Calculate dNBR (pre-fire NBR - post-fire NBR)
    d_nbr = pre_fire_nbr.subtract(post_fire_nbr).rename('dNBR').toFloat()

# Define severity classes based on the provided dNBR ranges
severity = (
    d_nbr.where(d_nbr.lt(-0.1), 0)
    .where(d_nbr.gte(-0.1).And(d_nbr.lte(0.1)), 1)
    .where(d_nbr.gt(0.1).And(d_nbr.lte(0.27)), 2)
    .where(d_nbr.gt(0.27).And(d_nbr.lte(0.66)), 3)
    .where(d_nbr.gt(0.66), 4)
)

# Display the burn severity index on the map
Map = geemap.Map()
Map.centerObject(pointBuffer, 15)

# Add the pre-fire RGB layer to the map
Map.addLayer(pre_fire_s2_median, vis_params, 'Pre-Fire RGB')

# Add the post-fire RGB layer to the map
Map.addLayer(post_fire_s2_median, vis_params, 'Post-Fire RGB')

# Display the dNBR layer on the map
Map.addLayer(d_nbr, d_nbr_vis_params, 'dNBR')

# Add the pointBuffer to the map
Map.addLayer(pointBuffer, {'color': 'FF0000'}, 'Buffer')

# Set visualization parameters for the severity index
severity_vis_params = {'min': 0, 'max': 4, 'palette': ['00FF00', 'FFFF00', 'FFA500', 'FF4500', 'FF0000']}
Map.addLayer(severity, severity_vis_params, 'Burn Severity Index')

# Create a legend
legend_title = 'Burn Severity Legend'
legend_labels = ['Enhanced Regrowth', 'Unburned', 'Low Severity', 'Moderate Severity', 'High Severity']
legend_colors = ['00FF00', 'FFFF00', 'FFA500', 'FF4500', 'FF0000']

# Add legend to the map
Map.add_legend(title=legend_title, labels=legend_labels, colors=legend_colors)

# Display the map
Map